/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as LoadingImport } from "./routes/loading";
import { Route as LinkImport } from "./routes/link";
import { Route as CreateImport } from "./routes/create";
import { Route as IndexImport } from "./routes/index";
import { Route as EpicLinkMemberImport } from "./routes/$epicLink/member";
import { Route as EpicLinkMainImport } from "./routes/$epicLink/main";
import { Route as EpicLinkJoinImport } from "./routes/$epicLink/join";
import { Route as EpicLinkDeleteImport } from "./routes/$epicLink/delete";

// Create/Update Routes

const LoadingRoute = LoadingImport.update({
  id: "/loading",
  path: "/loading",
  getParentRoute: () => rootRoute,
} as any);

const LinkRoute = LinkImport.update({
  id: "/link",
  path: "/link",
  getParentRoute: () => rootRoute,
} as any);

const CreateRoute = CreateImport.update({
  id: "/create",
  path: "/create",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const EpicLinkMemberRoute = EpicLinkMemberImport.update({
  id: "/$epicLink/member",
  path: "/$epicLink/member",
  getParentRoute: () => rootRoute,
} as any);

const EpicLinkMainRoute = EpicLinkMainImport.update({
  id: "/$epicLink/main",
  path: "/$epicLink/main",
  getParentRoute: () => rootRoute,
} as any);

const EpicLinkJoinRoute = EpicLinkJoinImport.update({
  id: "/$epicLink/join",
  path: "/$epicLink/join",
  getParentRoute: () => rootRoute,
} as any);

const EpicLinkDeleteRoute = EpicLinkDeleteImport.update({
  id: "/$epicLink/delete",
  path: "/$epicLink/delete",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/create": {
      id: "/create";
      path: "/create";
      fullPath: "/create";
      preLoaderRoute: typeof CreateImport;
      parentRoute: typeof rootRoute;
    };
    "/link": {
      id: "/link";
      path: "/link";
      fullPath: "/link";
      preLoaderRoute: typeof LinkImport;
      parentRoute: typeof rootRoute;
    };
    "/loading": {
      id: "/loading";
      path: "/loading";
      fullPath: "/loading";
      preLoaderRoute: typeof LoadingImport;
      parentRoute: typeof rootRoute;
    };
    "/$epicLink/delete": {
      id: "/$epicLink/delete";
      path: "/$epicLink/delete";
      fullPath: "/$epicLink/delete";
      preLoaderRoute: typeof EpicLinkDeleteImport;
      parentRoute: typeof rootRoute;
    };
    "/$epicLink/join": {
      id: "/$epicLink/join";
      path: "/$epicLink/join";
      fullPath: "/$epicLink/join";
      preLoaderRoute: typeof EpicLinkJoinImport;
      parentRoute: typeof rootRoute;
    };
    "/$epicLink/main": {
      id: "/$epicLink/main";
      path: "/$epicLink/main";
      fullPath: "/$epicLink/main";
      preLoaderRoute: typeof EpicLinkMainImport;
      parentRoute: typeof rootRoute;
    };
    "/$epicLink/member": {
      id: "/$epicLink/member";
      path: "/$epicLink/member";
      fullPath: "/$epicLink/member";
      preLoaderRoute: typeof EpicLinkMemberImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/create": typeof CreateRoute;
  "/link": typeof LinkRoute;
  "/loading": typeof LoadingRoute;
  "/$epicLink/delete": typeof EpicLinkDeleteRoute;
  "/$epicLink/join": typeof EpicLinkJoinRoute;
  "/$epicLink/main": typeof EpicLinkMainRoute;
  "/$epicLink/member": typeof EpicLinkMemberRoute;
}

export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/create": typeof CreateRoute;
  "/link": typeof LinkRoute;
  "/loading": typeof LoadingRoute;
  "/$epicLink/delete": typeof EpicLinkDeleteRoute;
  "/$epicLink/join": typeof EpicLinkJoinRoute;
  "/$epicLink/main": typeof EpicLinkMainRoute;
  "/$epicLink/member": typeof EpicLinkMemberRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/": typeof IndexRoute;
  "/create": typeof CreateRoute;
  "/link": typeof LinkRoute;
  "/loading": typeof LoadingRoute;
  "/$epicLink/delete": typeof EpicLinkDeleteRoute;
  "/$epicLink/join": typeof EpicLinkJoinRoute;
  "/$epicLink/main": typeof EpicLinkMainRoute;
  "/$epicLink/member": typeof EpicLinkMemberRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/create"
    | "/link"
    | "/loading"
    | "/$epicLink/delete"
    | "/$epicLink/join"
    | "/$epicLink/main"
    | "/$epicLink/member";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/create"
    | "/link"
    | "/loading"
    | "/$epicLink/delete"
    | "/$epicLink/join"
    | "/$epicLink/main"
    | "/$epicLink/member";
  id:
    | "__root__"
    | "/"
    | "/create"
    | "/link"
    | "/loading"
    | "/$epicLink/delete"
    | "/$epicLink/join"
    | "/$epicLink/main"
    | "/$epicLink/member";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CreateRoute: typeof CreateRoute;
  LinkRoute: typeof LinkRoute;
  LoadingRoute: typeof LoadingRoute;
  EpicLinkDeleteRoute: typeof EpicLinkDeleteRoute;
  EpicLinkJoinRoute: typeof EpicLinkJoinRoute;
  EpicLinkMainRoute: typeof EpicLinkMainRoute;
  EpicLinkMemberRoute: typeof EpicLinkMemberRoute;
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  LinkRoute: LinkRoute,
  LoadingRoute: LoadingRoute,
  EpicLinkDeleteRoute: EpicLinkDeleteRoute,
  EpicLinkJoinRoute: EpicLinkJoinRoute,
  EpicLinkMainRoute: EpicLinkMainRoute,
  EpicLinkMemberRoute: EpicLinkMemberRoute,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create",
        "/link",
        "/loading",
        "/$epicLink/delete",
        "/$epicLink/join",
        "/$epicLink/main",
        "/$epicLink/member"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create": {
      "filePath": "create.tsx"
    },
    "/link": {
      "filePath": "link.tsx"
    },
    "/loading": {
      "filePath": "loading.tsx"
    },
    "/$epicLink/delete": {
      "filePath": "$epicLink/delete.tsx"
    },
    "/$epicLink/join": {
      "filePath": "$epicLink/join.tsx"
    },
    "/$epicLink/main": {
      "filePath": "$epicLink/main.tsx"
    },
    "/$epicLink/member": {
      "filePath": "$epicLink/member.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
